@extends('fees.layout')

@section('title', 'Receipt History')

@section('content')
<div class="container-fluid">
<div class="d-flex justify-content-between align-items-center mb-4 border-bottom pb-3">
    <div>
        <h1 class="h4 mb-0 fw-bold">My Receipt History</h1>
        <p class="text-muted small mb-0">List of all receipts generated by you.</p>
    </div>
    <div class="d-flex gap-2">
        <button class="btn btn-sm btn-outline-secondary rounded-pill px-3" type="button" data-bs-toggle="collapse" data-bs-target="#filterPanel">
            <i class="bi bi-filter me-1"></i> Filters
        </button>
        <a href="{{ route('fees.receipts.index') }}" class="btn btn-sm btn-primary rounded-pill px-3">
            <i class="bi bi-arrow-clockwise me-1"></i> Refresh
        </a>
    </div>
</div>

{{-- Filters --}}
<div class="collapse mb-4 {{ request()->anyFilled(['q', 'payment_mode', 'start_date']) ? 'show' : '' }}" id="filterPanel">
    <div class="card border-0 shadow-sm rounded-4">
        <div class="card-body p-3">
            <form action="{{ route('fees.receipts.index') }}" method="GET" class="row g-3">
                <div class="col-md-4">
                    <label class="form-label small fw-bold text-muted text-uppercase">Search</label>
                    <input type="text" name="q" value="{{ request('q') }}" placeholder="Receipt No, Student, Adm No..." class="form-control form-control-sm shadow-none">
                </div>
                <div class="col-md-2">
                    <label class="form-label small fw-bold text-muted text-uppercase">Mode</label>
                    <select name="payment_mode" class="form-select form-select-sm shadow-none">
                        <option value="">All Modes</option>
                        <option value="CASH" {{ request('payment_mode') == 'CASH' ? 'selected' : '' }}>Cash</option>
                        <option value="UPI" {{ request('payment_mode') == 'UPI' ? 'selected' : '' }}>UPI</option>
                    </select>
                </div>
                <div class="col-md-2">
                    <label class="form-label small fw-bold text-muted text-uppercase">From</label>
                    <input type="date" name="start_date" value="{{ request('start_date') }}" class="form-control form-control-sm shadow-none">
                </div>
                <div class="col-md-2">
                    <label class="form-label small fw-bold text-muted text-uppercase">To</label>
                    <input type="date" name="end_date" value="{{ request('end_date') }}" class="form-control form-control-sm shadow-none">
                </div>
                <div class="col-md-2 d-flex align-items-end">
                    <button type="submit" class="btn btn-primary btn-sm w-100 rounded-pill">Apply</button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="card border-0 shadow-sm rounded-4 overflow-hidden">
    <div class="table-responsive">
        <table class="table table-hover align-middle mb-0">
            <thead class="bg-light">
                <tr class="small text-uppercase fw-bold text-muted" style="letter-spacing: 0.5px;">
                    <th class="px-4 py-3">Receipt No.</th>
                    <th class="py-3">Date</th>
                    <th class="py-3">Student / Admission</th>
                    <th class="py-3 text-end">Amount</th>
                    <th class="py-3 text-center">Mode</th>
                    <th class="py-3 text-center">Status</th>
                    <th class="px-4 py-3 text-end">Action</th>
                </tr>
            </thead>
            <tbody class="small">
                @forelse ($receipts as $receipt)
                    <tr>
                        <td class="px-4 fw-bold text-primary font-monospace">{{ $receipt->receipt_number }}</td>
                        <td>{{ optional(optional($receipt->payment)->payment_date)->format('d-m-Y H:i') }}</td>
                        <td>
                            <div class="fw-bold text-dark">{{ optional(optional(optional($receipt->payment)->feeAccount)->student)->student_name ?? '-' }}</div>
                            <div class="small text-muted font-monospace" style="font-size: 0.7rem;">{{ optional(optional(optional($receipt->payment)->feeAccount)->student)->admission_no ?? '-' }}</div>
                        </td>
                        <td class="text-end fw-bold font-monospace">₹{{ number_format((float) optional($receipt->payment)->amount, 2) }}</td>
                        <td class="text-center">
                            <span class="badge bg-light text-dark border fw-normal">{{ optional($receipt->payment)->payment_mode }}</span>
                        </td>
                        <td class="text-center">
                            <span class="badge rounded-pill py-1 px-3 
                                {{ optional($receipt->payment)->status === 'SUCCESS' ? 'bg-success-subtle text-success border border-success' : 'bg-danger-subtle text-danger border border-danger' }}">
                                {{ optional($receipt->payment)->status }}
                            </span>
                        </td>
                        <td class="px-4 text-end">
                            <div class="btn-group">
                                <a class="btn btn-sm btn-primary rounded-pill px-3 shadow-sm me-1" href="{{ route('fees.receipts.show', $receipt->receipt_id) }}">
                                    <i class="bi bi-eye me-1"></i> View
                                </a>
                                @if($receipt->payment?->account_id)
                                    <a class="btn btn-sm btn-outline-primary rounded-pill px-3 shadow-sm me-1" href="{{ route('fees.ledger', $receipt->payment->account_id) }}">
                                        <i class="bi bi-journal-text me-1"></i> Ledger
                                    </a>
                                @endif
                                @if(optional($receipt->payment)->status === 'SUCCESS')
                                    <button type="button" class="btn btn-sm btn-outline-danger rounded-pill px-3 shadow-sm" 
                                            onclick="openCancelModal('{{ route('fees.payments.cancel', $receipt->payment_id) }}', '{{ $receipt->receipt_number }}')">
                                        <i class="bi bi-x-circle me-1"></i> Cancel
                                    </button>
                                @endif
                            </div>
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td class="text-center py-5 text-muted" colspan="7">
                            <i class="bi bi-receipt fs-1 d-block mb-3 opacity-25"></i>
                            No receipts found.
                        </td>
                    </tr>
                @endforelse
            </tbody>
        </table>
    </div>
</div>
<div class="mt-4">{{ $receipts->links() }}</div>
</div>

{{-- Cancel Modal --}}
<div class="modal fade" id="cancelModal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content border-0 shadow-lg rounded-4">
            <div class="modal-header border-0 pb-0">
                <h5 class="modal-title fw-bold">Cancel Receipt <span id="cancelReceiptNo" class="text-primary"></span></h5>
                <button type="button" class="btn-close shadow-none" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form id="cancelForm" method="POST">
                @csrf
                <div class="modal-body py-4">
                    <div class="alert alert-warning small mb-3">
                        <i class="bi bi-exclamation-triangle me-2"></i>
                        This action will revert the student's fee balance and cannot be undone.
                    </div>
                    <div class="mb-3">
                        <label class="form-label small fw-bold text-muted text-uppercase">Cancellation Reason</label>
                        <textarea name="cancellation_reason" class="form-control shadow-none" rows="3" required placeholder="Enter why this receipt is being cancelled..."></textarea>
                    </div>
                </div>
                <div class="modal-footer border-0 pt-0">
                    <button type="button" class="btn btn-light rounded-pill px-4" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-danger rounded-pill px-4">Confirm Cancellation</button>
                </div>
            </form>
        </div>
    </div>
</div>

@push('scripts')
<script>
function openCancelModal(url, receiptNo) {
    document.getElementById('cancelForm').action = url;
    document.getElementById('cancelReceiptNo').innerText = '#' + receiptNo;
    var myModal = new bootstrap.Modal(document.getElementById('cancelModal'));
    myModal.show();
}
</script>
@endpush
@endsection
