@extends('fees.layout')

@section('title', 'Receipt '.$receipt->receipt_number)

@section('content')
<div class="mx-auto" style="max-width:820px">
    <div class="card shadow-sm">
        <div class="card-body p-4">
            <div class="d-flex justify-content-between align-items-start mb-3">
                <div>
                    <h3 class="mb-0">Vikas High School</h3>
                    <small class="text-muted">Official Fee Receipt</small>
                </div>
                <div class="text-end">
                    <h5 class="mb-0">Receipt</h5>
                    <div class="text-muted">#{{ $receipt->receipt_number }}</div>
                </div>
            </div>

            <div class="row mb-3">
                <div class="col-sm-6">
                    <div><strong>Student:</strong> {{ optional(optional($receipt->payment->feeAccount)->student)->student_name ?? '-' }}</div>
                    <div><strong>Admission No.:</strong> {{ optional(optional($receipt->payment->feeAccount)->student)->admission_no ?? '-' }}</div>
                    <div><strong>Father:</strong> {{ optional(optional($receipt->payment->feeAccount)->student)->father_name ?? '-' }}</div>
                </div>
                <div class="col-sm-6 text-sm-end">
                    <div><strong>Date:</strong> {{ optional($receipt->payment->payment_date)->format('d-m-Y H:i') }}</div>
                    <div><strong>Academic Year:</strong> {{ optional(optional($receipt->payment->feeAccount)->academicYear)->year_name ?? '-' }}</div>
                    <div><strong>Collector:</strong> {{ optional($receipt->payment->collector)->full_name ?? optional($receipt->payment->collector)->username ?? '-' }}</div>
                </div>
            </div>

            <div class="table-responsive mb-3">
                <table class="table table-borderless table-sm">
                    <thead>
                        <tr class="text-muted"><th>Description</th><th class="text-end">Amount (INR)</th></tr>
                    </thead>
                    <tbody>
                        <tr><td>Books Fee Paid</td><td class="text-end">{{ number_format((float) $receipt->payment->books_fee_paid, 2) }}</td></tr>
                        <tr><td>Tuition Fee Paid</td><td class="text-end">{{ number_format((float) $receipt->payment->tuition_fee_paid, 2) }}</td></tr>
                        <tr class="border-top"><td class="fw-semibold">Total Paid</td><td class="text-end fw-semibold">{{ number_format((float) $receipt->payment->amount, 2) }}</td></tr>
                    </tbody>
                </table>
            </div>

            <div class="row mb-3 small text-muted">
                <div class="col-sm-6">Remaining Balance: {{ number_format((float) $receipt->payment->feeAccount->remaining_balance, 2) }}</div>
                <div class="col-sm-6 text-sm-end">Payment Mode: {{ $receipt->payment->payment_mode }}</div>
            </div>

            <div class="d-flex justify-content-between align-items-center d-print-none">
                <div class="text-muted small">Generated by: {{ optional($receipt->payment->collector)->full_name ?? optional($receipt->payment->collector)->username ?? '-' }}</div>
                <div class="btn-group">
                    <a class="btn btn-outline-primary btn-sm" href="{{ route('fees.receipts.print', $receipt->id) }}?print_format=thermal">Thermal Print</a>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection
